package migration

import (
	"io"

	"meshium/internal/mod/discovery"
)

// SSHExecuter extends discovery.SSHExecuter with SFTP operations.
type SSHExecuter interface {
	Exec(cmd string) (string, string, int, error)
	IsAlive() bool
	Upload(src io.Reader, remotePath string) error
	Download(remotePath string, dst io.Writer) error
}

// StepCallback is called for each step result during migration.
type StepCallback func(msg WSMessage)

// WSMessage is the WebSocket message format for migration progress.
type WSMessage struct {
	Step   string `json:"step"`
	Status string `json:"status"`
	Value  string `json:"value,omitempty"`
	Error  string `json:"error,omitempty"`
}

// UserData holds user information collected from source.
type UserData struct {
	Name     string `json:"name"`
	UID      int    `json:"uid"`
	GID      int    `json:"gid"`
	HomeDir  string `json:"homeDir"`
	Shell    string `json:"shell"`
	Password string `json:"password,omitempty"` // from /etc/shadow
}

// GroupData holds group information collected from source.
type GroupData struct {
	Name string `json:"name"`
	GID  int    `json:"gid"`
}

// MigrationPlan is the plan generated by the planner.
type MigrationPlan struct {
	Source        discovery.SystemInfo `json:"source"`
	Target        discovery.SystemInfo `json:"target"`
	Categories    []string             `json:"categories"`
	Steps         []PlanStep           `json:"steps"`
	Warnings      []string             `json:"warnings,omitempty"`
	EstimatedTime string               `json:"estimatedTime,omitempty"`
}

type PlanStep struct {
	Category    string `json:"category"`
	Action      string `json:"action"`
	Description string `json:"description"`
	ItemCount   int    `json:"itemCount"`
}

// Migration is the DB model for a migration record.
type Migration struct {
	ID          int    `json:"id"`
	SourceID    int    `json:"sourceId"`
	TargetID    int    `json:"targetId"`
	Categories  string `json:"categories"`        // JSON array
	Status      string `json:"status"`            // pending, running, success, failed, failed_rollback
	Plan        string `json:"plan,omitempty"`    // JSON MigrationPlan
	Error       string `json:"error,omitempty"`
	CreatedAt   string `json:"createdAt"`
	CompletedAt string `json:"completedAt,omitempty"`
}

// MigrationStep is the DB model for a migration step.
type MigrationStep struct {
	ID          int    `json:"id"`
	MigrationID int    `json:"migrationId"`
	Category    string `json:"category"`
	Action      string `json:"action"`
	Status      string `json:"status"`
	Output      string `json:"output,omitempty"`
	Error       string `json:"error,omitempty"`
	StartedAt   string `json:"startedAt,omitempty"`
	CompletedAt string `json:"completedAt,omitempty"`
}

// MigrationBackup is the DB model for a migration backup.
type MigrationBackup struct {
	ID          int    `json:"id"`
	MigrationID int    `json:"migrationId"`
	ServerID    int    `json:"serverId"`
	Category    string `json:"category"`
	BackupPath  string `json:"backupPath"`
	BackupType  string `json:"backupType"`
	CreatedAt   string `json:"createdAt"`
}

// --- DTOs ---

type PlanRequest struct {
	SourceID    int      `json:"sourceId"`
	TargetID    int      `json:"targetId"`
	Categories  []string `json:"categories"`
	ConfigPaths []string `json:"configPaths,omitempty"`
}

type CreateMigrationRequest struct {
	SourceID    int      `json:"sourceId"`
	TargetID    int      `json:"targetId"`
	Categories  []string `json:"categories"`
	ConfigPaths []string `json:"configPaths,omitempty"`
}

type MigrationResponse struct {
	ID          int            `json:"id"`
	SourceID    int            `json:"sourceId"`
	TargetID    int            `json:"targetId"`
	Categories  []string       `json:"categories"`
	Status      string         `json:"status"`
	Plan        *MigrationPlan `json:"plan,omitempty"`
	Error       string         `json:"error,omitempty"`
	CreatedAt   string         `json:"createdAt"`
	CompletedAt string         `json:"completedAt,omitempty"`
	Steps       []MigrationStep `json:"steps,omitempty"`
}

// Collector and Applier interfaces are defined in categories.go
// to avoid circular dependency with CategoryData/BackupData types.
