package migration

import (
	"context"
	"fmt"

	"meshium/internal/mod/discovery"
	modssh "meshium/internal/mod/ssh"
	"meshium/internal/mod/transport"

	xssh "golang.org/x/crypto/ssh"
)

// --- Status constants ---

const (
	StatusPlanned        = "planned"
	StatusRunning        = "running"
	StatusCompleted      = "completed"
	StatusFailed         = "failed"
	StatusRollingBack    = "rolling_back"
	StatusRolledBack     = "rolled_back"
	StatusRollbackFailed = "rollback_failed"
	StatusInterrupted    = "interrupted" // set when a running migration is detected after a crash
	StatusResuming       = "resuming"    // set when an interrupted migration is being resumed
)

const (
	StepStatusPending   = "pending"
	StepStatusRunning   = "running"
	StepStatusCompleted = "completed"
	StepStatusFailed    = "failed"
	StepStatusApplied   = "applied" // step has been applied to the target (checkpoint marker)
)

// --- SSH and progress types ---

// SSHExecuter is the interface for executing commands and transferring
// files over an SSH connection. It is an alias for transport.SSHExecuter.
type SSHExecuter = transport.SSHExecuter

// StepCallback is called for each step result during migration.
type StepCallback func(msg WSMessage)

// WSMessage is the WebSocket message format for migration progress.
type WSMessage struct {
	Step   string `json:"step"`
	Status string `json:"status"`
	Value  string `json:"value,omitempty"`
	Error  string `json:"error,omitempty"`
}

// --- Data types ---

// UserData holds user information collected from source.
type UserData struct {
	Name     string `json:"name"`
	UID      int    `json:"uid"`
	GID      int    `json:"gid"`
	HomeDir  string `json:"homeDir"`
	Shell    string `json:"shell"`
	Password string `json:"password,omitempty"`
}

// GroupData holds group information collected from source.
type GroupData struct {
	Name string `json:"name"`
	GID  int    `json:"gid"`
}

// --- Plan types ---

// MigrationPlan is the plan generated by the planner and persisted to DB.
type MigrationPlan struct {
	ID              int                  `json:"id"`
	SourceServerID  int                  `json:"sourceServerId"`
	TargetServerID  int                  `json:"targetServerId"`
	Status          string               `json:"status"`
	Categories      []string             `json:"categories"`
	Source          discovery.SystemInfo `json:"source,omitempty"`
	Target          discovery.SystemInfo `json:"target,omitempty"`
	Steps           []PlanStep           `json:"steps,omitempty"`
	Warnings        []string             `json:"warnings,omitempty"`
	EstimatedTime   string               `json:"estimatedTime,omitempty"`
}

type PlanStep struct {
	Category    string `json:"category"`
	Action      string `json:"action"`
	Description string `json:"description"`
	ItemCount   int    `json:"itemCount"`
}

// --- DB models ---

// Migration is the DB model for a migration record.
type Migration struct {
	ID          int    `json:"id"`
	SourceID    int    `json:"sourceId"`
	TargetID    int    `json:"targetId"`
	Categories  string `json:"categories"`        // JSON array
	Status      string `json:"status"`
	Plan        string `json:"plan,omitempty"`    // JSON MigrationPlan
	Error       string `json:"error,omitempty"`
	CreatedAt   string `json:"createdAt"`
	CompletedAt string `json:"completedAt,omitempty"`
}

// MigrationStep is the DB model for a migration step.
type MigrationStep struct {
	ID          int    `json:"id"`
	MigrationID int    `json:"migrationId"`
	Category    string `json:"category"`
	Action      string `json:"action"`
	Status      string `json:"status"`
	Data        string `json:"data,omitempty"`     // JSON CategoryData
	Output      string `json:"output,omitempty"`
	Error       string `json:"error,omitempty"`
	StartedAt   string `json:"startedAt,omitempty"`
	CompletedAt string `json:"completedAt,omitempty"`
}

// MigrationBackup is the DB model for a migration backup.
type MigrationBackup struct {
	ID          int    `json:"id"`
	MigrationID int    `json:"migrationId"`
	ServerID    int    `json:"serverId"`
	Category    string `json:"category"`
	Data        string `json:"data"`              // JSON BackupData
	CreatedAt   string `json:"createdAt"`
}

// --- DTOs ---

type PlanRequest struct {
	SourceServerID int      `json:"sourceServerId"`
	TargetServerID int      `json:"targetServerId"`
	Categories     []string `json:"categories"`
	ConfigPaths    []string `json:"configPaths,omitempty"`
}

type MigrationResponse struct {
	ID          int             `json:"id"`
	SourceID    int             `json:"sourceId"`
	TargetID    int             `json:"targetId"`
	Categories  []string        `json:"categories"`
	Status      string          `json:"status"`
	Plan        *MigrationPlan  `json:"plan,omitempty"`
	Error       string          `json:"error,omitempty"`
	CreatedAt   string          `json:"createdAt"`
	CompletedAt string          `json:"completedAt,omitempty"`
	Steps       []MigrationStep `json:"steps,omitempty"`
}

// --- Interfaces (reused from transport) ---

// ConnectionPool provides SSH clients for a server.
type ConnectionPool = transport.ConnectionPool

// PoolAdapter wraps a transport.ConnectionPool to satisfy migration.ConnectionPool.
type PoolAdapter struct {
	Inner transport.ConnectionPool
}

func (a *PoolAdapter) Get(serverID int, cfg modssh.ServerConfig, hostKeyCallback xssh.HostKeyCallback) (SSHExecuter, error) {
	client, err := a.Inner.Get(serverID, cfg, hostKeyCallback)
	if err != nil {
		return nil, err
	}
	// The underlying *ssh.Client implements Upload/Download, so type-assert
	if s, ok := client.(SSHExecuter); ok {
		return s, nil
	}
	return nil, fmt.Errorf("SSH client does not support SFTP operations")
}

func (a *PoolAdapter) GetContext(ctx context.Context, serverID int, cfg modssh.ServerConfig, hostKeyCallback xssh.HostKeyCallback) (SSHExecuter, error) {
	client, err := a.Inner.GetContext(ctx, serverID, cfg, hostKeyCallback)
	if err != nil {
		return nil, err
	}
	if s, ok := client.(SSHExecuter); ok {
		return s, nil
	}
	return nil, fmt.Errorf("SSH client does not support SFTP operations")
}

// AESKeyProvider exposes the AES key needed to decrypt stored credentials.
type AESKeyProvider = transport.AESKeyProvider

// HostKeyStore provides host key verification callbacks.
type HostKeyStore = transport.HostKeyStore

// Collector and Applier interfaces are defined in categories.go
// to avoid circular dependency with CategoryData/BackupData types.
