package migration

import (
	"context"
	"encoding/json"
	"strings"
	"testing"
)

const sampleIptablesSave = `# Generated by iptables-save
*filter
:INPUT ACCEPT [0:0]
-A INPUT -p tcp --dport 22 -j ACCEPT
COMMIT
`

const sampleUfwStatus = `Status: active

To                         Action      From
--                         ------      ----
22/tcp                     ALLOW       Anywhere
`

// The collect command is `iptables-save 2>/dev/null || ufw status 2>/dev/null`.
// When iptables-save is absent the ufw branch captures human-readable status
// text — which Apply then pipes into `iptables-restore 2>/dev/null` with the
// exit code discarded. iptables-restore rejects it, the target comes up with no
// firewall rules, and the step reports success. Content that is not in
// iptables-save format must not be stored as restorable.
func TestUsersCollectRejectsUfwStatusAsFirewallRules(t *testing.T) {
	ssh := newMockSSH()
	ssh.addOutput("cat /etc/passwd", "root:x:0:0:root:/root:/bin/bash\n")
	ssh.addOutput("cat /etc/group", "root:x:0:\n")
	ssh.addOutput("iptables-save", sampleUfwStatus) // the || fell through to ufw

	data, err := (&UsersCollector{}).Collect(context.Background(), ssh)
	if err != nil {
		t.Fatalf("Collect: %v", err)
	}
	var ud UsersData
	if err := json.Unmarshal(data.Data, &ud); err != nil {
		t.Fatalf("unmarshal: %v", err)
	}
	if ud.Firewall != "" {
		t.Errorf("ufw status text stored as restorable firewall rules:\n%s", ud.Firewall)
	}
}

func TestUsersCollectAcceptsIptablesSave(t *testing.T) {
	ssh := newMockSSH()
	ssh.addOutput("cat /etc/passwd", "root:x:0:0:root:/root:/bin/bash\n")
	ssh.addOutput("cat /etc/group", "root:x:0:\n")
	ssh.addOutput("iptables-save", sampleIptablesSave)

	data, err := (&UsersCollector{}).Collect(context.Background(), ssh)
	if err != nil {
		t.Fatalf("Collect: %v", err)
	}
	var ud UsersData
	if err := json.Unmarshal(data.Data, &ud); err != nil {
		t.Fatalf("unmarshal: %v", err)
	}
	if !strings.Contains(ud.Firewall, "*filter") {
		t.Errorf("real iptables-save output was not stored: %q", ud.Firewall)
	}
}

// Defense in depth for records collected before the fix: Apply must not pipe
// non-iptables-save content into iptables-restore.
func TestUsersApplySkipsNonRestorableFirewall(t *testing.T) {
	ud := UsersData{Firewall: sampleUfwStatus, CronJobs: map[string]string{}}
	raw, _ := json.Marshal(ud)

	ssh := newMockSSH()
	if err := (&UsersApplier{}).Apply(context.Background(), ssh, CategoryData{Type: "users", Data: raw}, nil); err != nil {
		t.Fatalf("Apply: %v", err)
	}
	for _, cmd := range ssh.commands {
		if strings.Contains(cmd, "iptables-restore") {
			t.Fatalf("ufw status text piped into iptables-restore: %q", cmd)
		}
	}
}

// The crontab backup command emitted `<crontab body>` and THEN `---user---`,
// while the parser expected marker-first (`user\ncontent`). Verified live:
//
//	$ cut -d: -f1 /etc/passwd | while read u; do crontab -u $u -l 2>/dev/null && echo "---$u---"; done
//	0 3 * * * /usr/local/bin/backup.sh
//	30 4 * * 0 apt-get update
//	---root---
//
// Split on "---" that keys the body block by its own first cron line, and the
// block holding the real username is a single line and gets discarded — so a
// single-entry crontab vanished from the backup entirely, and multi-entry
// crontabs were stored under a garbage user.
func TestUsersBackupParsesCrontabsPerUser(t *testing.T) {
	ssh := newMockSSH()
	ssh.addOutput("cat /etc/passwd", "root:x:0:0:root:/root:/bin/bash\ndeploy:x:1000:1000::/home/deploy:/bin/bash\n")
	ssh.addOutput("cat /etc/group", "root:x:0:\n")
	// What the marker-first command actually prints for two users.
	ssh.addOutput("crontab", strings.Join([]string{
		"===MESHIUM-CRON:root===",
		"0 3 * * * /usr/local/bin/backup.sh",
		"30 4 * * 0 apt-get update",
		"===MESHIUM-CRON:deploy===",
		"*/5 * * * * /home/deploy/poll.sh",
		"",
	}, "\n"))

	backup, err := (&UsersApplier{}).Backup(context.Background(), ssh)
	if err != nil {
		t.Fatalf("Backup: %v", err)
	}
	var ub UsersBackup
	if err := json.Unmarshal(backup.Data, &ub); err != nil {
		t.Fatalf("unmarshal: %v", err)
	}

	if got := ub.CronJobs["root"]; !strings.Contains(got, "backup.sh") || !strings.Contains(got, "apt-get update") {
		t.Errorf("root crontab wrong: %q (all: %v)", got, ub.CronJobs)
	}
	if got := ub.CronJobs["deploy"]; !strings.Contains(got, "poll.sh") {
		t.Errorf("deploy single-line crontab lost: %q (all: %v)", got, ub.CronJobs)
	}
	for user := range ub.CronJobs {
		if strings.Contains(user, "*") || strings.Contains(user, "/") {
			t.Errorf("garbage crontab key %q — a cron line stored as a username", user)
		}
	}
}
