#!/usr/bin/env bash
#
# validate-fresh-clone.sh — local mirror of CI's "fresh-clone build guard".
#
# WHY: v1.5.0-beta.1/beta.2 shipped a tag tarball that would not build, because
# source files existed in the committer's working tree but were never committed
# (an over-broad .gitignore silently swallowed them). A normal checkout hides
# this — it carries whatever the committer had on disk. This script reproduces
# the exact conditions a user hits when they clone a tag: it builds ONLY tracked
# content, from a `git archive` of HEAD.
#
# This is NON-DESTRUCTIVE: it never touches your working tree. It materializes a
# throwaway tree under a temp dir, builds there, and removes it on exit.
#
# It does NOT perform a migration and needs no network beyond `go mod download`
# / `npm ci` that the build itself requires.
#
# Exit non-zero on the first failed guard. Intended to be run before tagging.

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
	echo "error: not inside a git work tree ($repo_root)" >&2
	exit 2
fi

echo "==> Guard 1/3: no tracked source file is swallowed by .gitignore"
# A source file that is BOTH tracked AND matched by a .gitignore rule is the
# fragile state that shipped in beta.1/beta.2: any NEW sibling created in that
# directory is silently ignored by `git add`. `--no-index` makes check-ignore
# evaluate tracked paths (it normally skips them).
ignored="$(git ls-files -- 'cmd/**' 'internal/**' 'web/src/**' \
	| git check-ignore --no-index --stdin -v || true)"
if [ -n "$ignored" ]; then
	echo "FAIL: tracked source file(s) match a .gitignore rule — new siblings will be silently uncommitted:" >&2
	echo "$ignored" >&2
	exit 1
fi
echo "    OK: no tracked source file is matched by a .gitignore rule."

work="$(mktemp -d "${TMPDIR:-/tmp}/meshium-fresh.XXXXXX")"
cleanup() { rm -rf "$work"; }
trap cleanup EXIT

echo "==> Materializing a tag-like tree (tracked files only) in $work"
git archive HEAD | tar -x -C "$work"

echo "==> Guard 2/3: embed output is not shipped in the tree"
if [ -e "$work/cmd/server/web/build" ]; then
	echo "FAIL: cmd/server/web/build is tracked. The embedded frontend must be generated by the build, not committed." >&2
	exit 1
fi
echo "    OK: cmd/server/web/build is absent (generated at build time)."

echo "==> Guard 3/3: make build (frontend + Go) in the tag-like tree"
if ! command -v make >/dev/null 2>&1; then
	echo "error: 'make' not found; cannot run the build guard" >&2
	exit 2
fi
( cd "$work" && make build && go vet ./... && go test ./... -count=1 )

echo "==> PASS: tag-like tree builds, vets, and tests from tracked files only."
